name: update data
on:
  workflow_dispatch:


jobs:
  update-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download data
        run: |
          curl https://donnees.roulez-eco.fr/opendata/instantane --output data.zip
          unzip data.zip
          mv *.xml data.xml

      - name: Clean data
        run: |
          ls -lrt
          echo ok
