name: update data
on:
  workflow_dispatch:


jobs:
  update-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Download data
        run: |
          curl https://donnees.roulez-eco.fr/opendata/instantane --output data.zip
          unzip data.zip
          mv *.xml data.xml

      - name: Clean data
        run: |
          mv data.xml price-explorer/.
          cd price-explorer/
          ./gradlew bootRun
          ls -lrt
          echo "ok"
