name: update data
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Download data
        run: |
          curl https://donnees.roulez-eco.fr/opendata/instantane --output data.zip
          unzip data.zip
          mv *.xml data.xml
      - name: Clean data
        run: |
          rm -rf data*.csv
          mv data.xml price-explorer/.
          cd price-explorer/
          ./gradlew bootRun
          mv data*.csv ../.
          echo "ok"
      - name: Push result
        run: |
         git config --global user.email "tkhadir.dev@gmail.com"
         git config --global user.name "tkhadir"
         git add data*.csv
         git commit -m "feat: add results"
         git push origin
