# This is a basic workflow to help you get started with Actions

name: Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup directories
        run: |
          rm -rf backup-*
          rm -rf archive-*
      - name: Update repo
        run: |
          git config --global user.email "tkhadir.dev@gmail.com"
          git config --global user.name "tkhadir"
          git add archive-*
          git add backup-*
          git commit -m "feat: cleanup results"
          git push origin
          echo "ok"
