name: update data
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 10 * * *'

permissions:
  contents: write

jobs:
  update-data-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Download data
        run: |
          curl https://donnees.roulez-eco.fr/opendata/instantane --output data.zip
          unzip --version
          unzip data.zip
          ls -lrt
          mv PrixCarburants_instantane.xml data.xml
      - name: Clean data
        run: |
          ls -lrt data*.csv
          echo "saving old data"
          now=$(date +%F_%H-%M-%S)
          yday=$(date  --date="yesterday" +"%Y-%m-%d")
          mkdir archive-$yday
          mv data*.csv archive-$yday/.
          echo "check old data"
          ls -lrt
          mv data.xml price-explorer/.
          cd price-explorer/
          ./gradlew bootRun
          mv data*.csv ../.
          rm -rf data.xml
          echo "ok"
      - name: Push result
        run: |
         git config --global user.email "tkhadir.dev@gmail.com"
         git config --global user.name "tkhadir"
         git add data*.csv
         git add archive-*
         git commit -m "feat: add results"
         git push origin
